project:
  type: website

website:
  title: "Rene Valenzuela"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - talks.qmd
  page-footer: 
    background: light
    left: Copyright 2025, René Valenzuela
    right: Thus website is built with [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true
    page-layout: full
