project:
  type: website

website:
  description: "First steps in learning about and applying causal inference to answer causal questions"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "causal musings"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
execute:
  echo: false


